"""initial_schema

Revision ID: 90e4b7b5e523
Revises: 
Create Date: 2026-03-14 17:38:09.616763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e4b7b5e523'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_phone', 'users', ['phone'], unique=False)
    op.create_table('elections',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_election_created_at', 'elections', ['created_at'], unique=False)
    op.create_index('idx_election_dates', 'elections', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_election_end_date', 'elections', ['end_date'], unique=False)
    op.create_index('idx_election_is_public', 'elections', ['is_public'], unique=False)
    op.create_index('idx_election_start_date', 'elections', ['start_date'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_role_links',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_user_role_link_role_id', 'user_role_links', ['role_id'], unique=False)
    op.create_index('idx_user_role_link_user_id', 'user_role_links', ['user_id'], unique=False)
    op.create_index('idx_user_role_link_user_role', 'user_role_links', ['user_id', 'role_id'], unique=False)
    op.create_table('candidates',
    sa.Column('election_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_candidate_election_id', 'candidates', ['election_id'], unique=False)
    op.create_table('election_access',
    sa.Column('election_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_election_access_election_id', 'election_access', ['election_id'], unique=False)
    op.create_index('idx_election_access_election_user', 'election_access', ['election_id', 'user_id'], unique=False)
    op.create_index('idx_election_access_user_id', 'election_access', ['user_id'], unique=False)
    op.create_table('election_results_cache',
    sa.Column('election_id', sa.String(length=36), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_election_results_cache_updated_at', 'election_results_cache', ['updated_at'], unique=False)
    op.create_table('election_settings',
    sa.Column('election_id', sa.String(length=36), nullable=False),
    sa.Column('allow_revoting', sa.Boolean(), nullable=False),
    sa.Column('max_votes', sa.Integer(), nullable=False),
    sa.Column('require_auth', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('election_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_attachment_candidate_id', 'attachments', ['candidate_id'], unique=False)
    op.create_index('idx_attachment_election_id', 'attachments', ['election_id'], unique=False)
    op.create_index('idx_attachment_uploaded_at', 'attachments', ['uploaded_at'], unique=False)
    op.create_index('idx_attachment_user_id', 'attachments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_attachment_user_id', table_name='attachments')
    op.drop_index('idx_attachment_uploaded_at', table_name='attachments')
    op.drop_index('idx_attachment_election_id', table_name='attachments')
    op.drop_index('idx_attachment_candidate_id', table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('election_settings')
    op.drop_index('idx_election_results_cache_updated_at', table_name='election_results_cache')
    op.drop_table('election_results_cache')
    op.drop_index('idx_election_access_user_id', table_name='election_access')
    op.drop_index('idx_election_access_election_user', table_name='election_access')
    op.drop_index('idx_election_access_election_id', table_name='election_access')
    op.drop_table('election_access')
    op.drop_index('idx_candidate_election_id', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index('idx_user_role_link_user_role', table_name='user_role_links')
    op.drop_index('idx_user_role_link_user_id', table_name='user_role_links')
    op.drop_index('idx_user_role_link_role_id', table_name='user_role_links')
    op.drop_table('user_role_links')
    op.drop_table('user_profiles')
    op.drop_index('idx_election_start_date', table_name='elections')
    op.drop_index('idx_election_is_public', table_name='elections')
    op.drop_index('idx_election_end_date', table_name='elections')
    op.drop_index('idx_election_dates', table_name='elections')
    op.drop_index('idx_election_created_at', table_name='elections')
    op.drop_table('elections')
    op.drop_index('idx_user_phone', table_name='users')
    op.drop_index('idx_user_created_at', table_name='users')
    op.drop_table('users')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
